opts = init();

if (isunix == 1)
    mex ('superpixel_mex.cpp', 'SLICSuperpixel.cpp', sprintf('%s/src/mc_convert/mc_convert/mc_convert.cpp',opts.root_dir), ...
    ['-I',sprintf('%s/src/mc_convert/mc_convert',opts.root_dir)], ['-I',opts.tbb_inc_dir], '-ltbb', 'CXXFLAGS="\$CXXFLAGS', '-std=c++0x', '-fpermissive"', '-DHAS_OPENCV', ...
    ['-I',opts.opencv_inc_dir], ['-L',opts.opencv_lib_dir], ...
    '-lopencv_core', '-lopencv_imgproc', '-lopencv_highgui', ...
    ['-I',sprintf('%s/src/mexopencv/include',opts.root_dir)], ['-L',sprintf('%s/src/mexopencv/lib',opts.root_dir)], '-lMxArray')
else
    mex('superpixel_mex.cpp', 'SLICSuperpixel.cpp', sprintf('%s/src/mc_convert/mc_convert/mc_convert.cpp',opts.root_dir), ...
        ['-I"',sprintf('%s/src/mc_convert/mc_convert',opts.root_dir),'"'], ['-I"',opts.tbb_inc_dir,'"'], '-ltbb', '-DHAS_OPENCV', ...
        ['-I"',opts.opencv_inc_dir,'"'],['-L"',opts.opencv_lib_dir,'"'], ...
        ['-lopencv_core', opts.opencv_version], ['-lopencv_imgproc', opts.opencv_version], ...
        ['-lopencv_highgui', opts.opencv_version], ['-lopencv_features2d', opts.opencv_version], ['-lopencv_calib3d', opts.opencv_version])
end


disp('Done!');
