opts = init();

if (isunix == 1)
    mex ('sgbm_mex.cpp', sprintf('%s/src/mc_convert/mc_convert/mc_convert.cpp',opts.root_dir), ...
        ['-I',sprintf('%s/src/mc_convert/mc_convert',opts.root_dir)], '-DHAS_OPENCV', ...
        ['-I',opts.opencv_inc_dir], ['-L',opts.opencv_lib_dir], ...
        '-lopencv_core', '-lopencv_imgproc', '-lopencv_highgui', '-lopencv_features2d', '-lopencv_calib3d')
else
    mex('sgbm_mex.cpp', sprintf('%s/src/mc_convert/mc_convert/mc_convert.cpp',opts.root_dir), ...
        ['-I"',sprintf('%s/src/mc_convert/mc_convert',opts.root_dir),'"'],'-DHAS_OPENCV', ...
        ['-I"',opts.opencv_inc_dir,'"'],['-L"',opts.opencv_lib_dir,'"'], ...
        ['-lopencv_core', opts.opencv_version], ['-lopencv_imgproc', opts.opencv_version], ...
        ['-lopencv_highgui', opts.opencv_version], ['-lopencv_features2d', opts.opencv_version], ['-lopencv_calib3d', opts.opencv_version])
end

mex compute_3D_point_cloud_mex.cpp

disp('Done SGM and PointCloud!');
